Projects/Data/DTO/Challenge/ChallengeResponseDTO.swift
Projects/Domain/Entity/Challenge.swift
Projects/Presentation/Home/Implementations/NoneChallengeHome/NoneChallengeHomeViewController.swift
Projects/Presentation/Home/Implementations/NoneChallengeHome/NoneChallengeHomeViewModel.swift
Projects/Presentation/Home/Implementations/NoneChallengeHome/Views/ChallengeImageCell.swift
Projects/Presentation/Home/Implementations/NoneChallengeHome/Views/ChallengePresentationModel.swift
Projects/Presentation/Project.swift
Tuist/Dependencies.swift
Tuist/ProjectDescriptionHelpers/TargetDependency+SPM.swift

- #145 
KingFisher 추가했습니다. 
기존에 `Etag`를 활용한 캐싱방법을 시도해볼려했으나, 저희 서버에서 `ETag`를 지원을 안하기에 만료에 대한 별도의 캐시 정책이 있는 KingFisher를 사용하기로 결정했습니다.

[FEAT]: Image 캐싱 라이브러이 추가

---

Projects/DesignSystem/Sources/Card/ProofChallenge/ProofChallengeCell.swift
Projects/DesignSystem/Sources/Card/ProofChallenge/ProofChallengeCellModel.swift
Projects/Presentation/MyPage/Implementations/EndedChallange/EndedChallangeViewController.swift
Projects/Presentation/MyPage/Implementations/MyPageContainer.swift
Projects/Presentation/MyPage/Implementations/MyPageCoordinator.swift
Projects/Presentation/MyPage/Implementations/MyPageViewModel.swift
Projects/Presentation/MyPage/Implementations/ProofChallenge/ProofChallengeContainer.swift
Projects/Presentation/MyPage/Implementations/ProofChallenge/ProofChallengeCoodinator.swift
Projects/Presentation/MyPage/Implementations/ProofChallenge/ProofChallengeViewController.swift
Projects/Presentation/MyPage/Implementations/ProofChallenge/ProofChallengeViewModel.swift

- #156 
인증 횟수 상세화면 (인증 내역 컬렉션 뷰 리스트)
- 톱니 이미지는 Ended Challenge 와 합친 후 수정 하겠습니다 (저번에 파일 분명히 바꿨는데 날라갔나봐요..)

[FEAT]: 인증횟수 목록 화면 UI 구현

---

Projects/Presentation/MyPage/Implementations/Setting/SettingCoordinator.swift
Projects/Presentation/Report/Implementations/ReportContainer.swift
Projects/Presentation/Report/Implementations/ReportCoordinator.swift
Projects/Presentation/Report/Implementations/ReportViewController.swift
Projects/Presentation/Report/Interfaces/Report.swift
Projects/Presentation/Report/Interfaces/ReportType.swift

- #166 
datasource를 제거하고 API 호출 및 유지 & 보수성이 용이하게 enum 타입을 사용한 형태로 변경하였습니다.

[REFACT] 신고하기 & 문의하기 개선

---

Projects/Core/Extensions/UIStackView+Extension.swift
Projects/DesignSystem/Sources/SemgnetControl/PhotiSegmentControl.swift
Projects/DesignSystem/Sources/SemgnetControl/SegmentButton.swift

[FEAT]: Photi Segmented Control 구현

---

Projects/App/Sources/AppContainer.swift
Projects/Data/DTO/FindId/FindIdRequestDTO.swift
Projects/Data/DataMapper/FindIdDataMapper.swift
Projects/Data/Repository/Implementations/FindIdRepositoryImpl/FindIdAPI.swift
Projects/Data/Repository/Implementations/FindIdRepositoryImpl/FindIdRepositoryImpl.swift
Projects/Domain/Repository/Interfaces/FindIdRepository.swift
Projects/Domain/UseCase/Implementations/FindIdUseCaseImpl.swift
Projects/Domain/UseCase/Interfaces/FindIdUseCase.swift
Projects/Presentation/LogIn/Implementations/FindId/FindIdContainer.swift
Projects/Presentation/LogIn/Implementations/FindId/FindIdViewController.swift
Projects/Presentation/LogIn/Implementations/FindId/FindIdViewModel.swift
Projects/Presentation/LogIn/Implementations/FindPassword/FindPasswordContainer.swift
Projects/Presentation/LogIn/Implementations/LogInContainer.swift
Projects/Presentation/MyPage/Implementations/ChangePassword/ChangePasswordViewController.swift
Projects/Presentation/MyPage/Implementations/ChangePassword/ChangePasswordViewModel.swift

- #182 
아이디 찾기 API 연결작업입니다
- 아이디 찾기 요청 성공 & 실패 & 네트워크 에러 case들에 각각 대응하였습니다

[FEAT]: 아이디 찾기 API 구현

---

Projects/App/Sources/AppContainer.swift
Projects/App/Sources/AppCoordinator.swift
Projects/App/Sources/AppViewController.swift
Projects/Data/DTO/Resign/ResignRequestDTO.swift
Projects/Data/DataMapper/ResignDataMapper.swift
Projects/Data/Repository/Implementations/ResignRepositoryImpl/ResignAPI.swift
Projects/Data/Repository/Implementations/ResignRepositoryImpl/ResignRepositoryImpl.swift
Projects/Domain/Repository/Interfaces/ResginRepository.swift
Projects/Domain/UseCase/Implementations/ResignUseCaseImpl.swift
Projects/Domain/UseCase/Interfaces/ResignUseCase.swift
Projects/Presentation/Challenge/Implementations/Member/Participant/ParticipantViewController.swift
Projects/Presentation/MyPage/Implementations/MyPageContainer.swift
Projects/Presentation/MyPage/Implementations/MyPageCoordinator.swift
Projects/Presentation/MyPage/Implementations/MyPageViewController.swift
Projects/Presentation/MyPage/Implementations/ProfileEdit/ProfileEditContainer.swift
Projects/Presentation/MyPage/Implementations/ProfileEdit/ProfileEditCoordinator.swift
Projects/Presentation/MyPage/Implementations/ProfileEdit/Resign/ResignContainer.swift
Projects/Presentation/MyPage/Implementations/ProfileEdit/Resign/ResignCoordinator.swift
Projects/Presentation/MyPage/Implementations/ProfileEdit/Resign/ResignPassword/ResignAuthContainer.swift
Projects/Presentation/MyPage/Implementations/ProfileEdit/Resign/ResignPassword/ResignAuthCoordinator.swift
Projects/Presentation/MyPage/Implementations/ProfileEdit/Resign/ResignPassword/ResignAuthViewController.swift
Projects/Presentation/MyPage/Implementations/ProfileEdit/Resign/ResignPassword/ResignAuthViewModel.swift
Projects/Presentation/MyPage/Implementations/ProfileEdit/Resign/ResignViewController.swift
Projects/Presentation/MyPage/Implementations/ProfileEdit/Resign/ResignViewModel.swift
Projects/Presentation/MyPage/Implementations/Setting/SettingContainer.swift
Projects/Presentation/MyPage/Implementations/Setting/SettingCoordinator.swift
Projects/Presentation/MyPage/Interfaces/MyPage.swift
Projects/Presentation/Report/Implementations/ReportContainer.swift
Projects/Presentation/Report/Implementations/ReportViewController.swift

- #183 
탈퇴하기 API 연결 완료헀습니다.
https://github.com/user-attachments/assets/559e411e-9b99-490a-bf39-cf61b41e0d6d
- 탭바 전환하는 로직 혹시 개선할 방향 보이면 말씀 부탁드립니다..!
- 탭바 이미지가 좀 작은것 같은데.. 아닌것 같기도하고.. 어떻게 보이시나요..? Figma보면 비슷한거 같기도해서요

[FEAT]: 탈퇴하기 API 연결

---

Projects/App/Sources/AppContainer.swift
Projects/Presentation/Report/Implementations/ReportViewController.swift

- #207
cell의 정보가 잘못 표기 되었던 문제를 수정하였습니다.
불필요한 코드를 제거 했습니다.

[REFACT]: 코드 수정사항 반영

---

Projects/Data/DTO/Challenge/MyChallenge/MyChallengesResponseDTO.swift
Projects/Data/DataMapper/ChallengeDataMapper.swift
Projects/Data/Repository/Implementations/ChallengeRepositoryImpl/ChallengeAPI.swift
Projects/Data/Repository/Implementations/ChallengeRepositoryImpl/ChallengeRepositoryImpl.swift
Projects/DesignSystem/Sources/Popup/Alert/UIViewController+Alert.swift
Projects/Domain/Entity/APIError.swift
Projects/Domain/Entity/ChallengeSummary.swift
Projects/Domain/Repository/Interfaces/ChallengeRepository.swift
Projects/Domain/UseCase/Implementations/ChallengeUseCaseImpl.swift
Projects/Domain/UseCase/Implementations/HomeUseCaseImpl.swift
Projects/Domain/UseCase/Interfaces/ChallengeUseCase.swift
Projects/Domain/UseCase/Interfaces/HomeUseCase.swift
Projects/Presentation/Challenge/Implementations/Member/Feed/FeedViewModel.swift
Projects/Presentation/Home/Implementations/ChallengeHome/ChallengeHomeContainer.swift
Projects/Presentation/Home/Implementations/ChallengeHome/ChallengeHomeCoordinator.swift
Projects/Presentation/Home/Implementations/ChallengeHome/ChallengeHomeViewController.swift
Projects/Presentation/Home/Implementations/ChallengeHome/ChallengeHomeViewModel.swift
Projects/Presentation/Home/Implementations/ChallengeHome/Views/HomeBottomView/HomeBottomView.swift
Projects/Presentation/Home/Implementations/ChallengeHome/Views/HomeBottomView/HomeMyChallengeCell.swift
Projects/Presentation/Home/Implementations/ChallengeHome/Views/HomeBottomView/MyChallengePresentationModel.swift
Projects/Presentation/Home/Implementations/ChallengeHome/Views/MyChallengeFeedPresentationModel.swift
Projects/Presentation/Home/Implementations/ChallengeHome/Views/ProofChallegneCell/ChallengeImageView.swift
Projects/Presentation/Home/Implementations/ChallengeHome/Views/ProofChallegneCell/ChallengeTitleView.swift
Projects/Presentation/Home/Implementations/ChallengeHome/Views/ProofChallegneCell/ProofChallengeCell.swift

- #142 
- Home API 연결 완료했습니다.
- 로그인 attach & detach 는 추후 로그인 수정 후 구현할 예정입니다. 
- Challenge 터치시 연결은 추후 Challenge 파티원 / 소개 API 완료 후 연결 예정입니다.

[FEAT]: Home(회원 챌린지)시에 연동 완료 

---

Projects/Core/Project.swift
Projects/Data/Project.swift
Projects/Domain/Project.swift
Projects/Presentation/Project.swift

- #226
interface(Home, Challenge, ...)과 자주 의존되는 모듈(Entity,..)을 Static Library에서 Dynamic Framework로 변경했습니다.
이로 인해서 증분 빌드에서 1.8 -> 1.3 으로 개선되었습니다. 
특히나, 여러 모듈에서 의존하는 모듈인 Entity의 인터페이스가 수정될 경우는 7~8초에서 4~5초로 2배가량 개선되었습니다.

[INFRA]: interface 및 자주 참조되는 모듈 static에서 dynamic으로 변경

---

Projects/App/Sources/AppCoordinator.swift
Projects/DesignSystem/Sources/Chip/IconChip/IconChip.swift
Projects/Presentation/SearchChallenge/Implementations/SearchChallengeContainer.swift
Projects/Presentation/SearchChallenge/Implementations/SearchChallengeCoordinator.swift
Projects/Presentation/SearchChallenge/Implementations/SearchChallengeViewController.swift
Projects/Presentation/SearchChallenge/Implementations/SearchChallengeViewModel.swift
Projects/Presentation/SearchChallenge/Implementations/SearchResult/ChallengeTitleResult/ChallengeTitleResultContainer.swift
Projects/Presentation/SearchChallenge/Implementations/SearchResult/ChallengeTitleResult/ChallengeTitleResultCoordinator.swift
Projects/Presentation/SearchChallenge/Implementations/SearchResult/ChallengeTitleResult/ChallengeTitleResultViewController.swift
Projects/Presentation/SearchChallenge/Implementations/SearchResult/ChallengeTitleResult/ChallengeTitleResultViewModel.swift
Projects/Presentation/SearchChallenge/Implementations/SearchResult/HashTagResult/HashTagResultContainer.swift
Projects/Presentation/SearchChallenge/Implementations/SearchResult/HashTagResult/HashTagResultCoordinator.swift
Projects/Presentation/SearchChallenge/Implementations/SearchResult/HashTagResult/HashTagResultViewController.swift
Projects/Presentation/SearchChallenge/Implementations/SearchResult/HashTagResult/HashTagResultViewModel.swift
Projects/Presentation/SearchChallenge/Implementations/SearchResult/SearchResultContainer.swift
Projects/Presentation/SearchChallenge/Implementations/SearchResult/SearchResultCoordinator.swift
Projects/Presentation/SearchChallenge/Implementations/SearchResult/SearchResultViewController.swift
Projects/Presentation/SearchChallenge/Implementations/SearchResult/SearchResultViewModel.swift
Projects/Presentation/SearchChallenge/Implementations/SearchResult/Views/RecentSearchInputCell.swift
Projects/Presentation/SearchChallenge/Implementations/SearchResult/Views/RecentSearchInputView.swift

[FEAT]: 검색 결과 화면 구현 

---

Projects/Presentation/Challenge/Implementations/ChallengeOrganize/ChallengeGoal/ChallengeGoalContainer.swift
Projects/Presentation/Challenge/Implementations/ChallengeOrganize/ChallengeGoal/ChallengeGoalViewController.swift
Projects/Presentation/Challenge/Implementations/ChallengeOrganize/ChallengeGoal/ChallengeGoalViewModel.swift
Projects/Presentation/Challenge/Implementations/ChallengeOrganize/ChallengeName/ChallengeNameContainer.swift
Projects/Presentation/Challenge/Implementations/ChallengeOrganize/ChallengeName/ChallengeNameViewController.swift
Projects/Presentation/Challenge/Implementations/ChallengeOrganize/ChallengeName/ChallengeNameViewModel.swift
Projects/Presentation/Challenge/Implementations/ChallengeOrganize/ChallengeOrganizeCoordinator.swift

- #269 
챌린지 OrganizeMode를 적용하여 UI를 mode에 따라 다르게 적용하였습니다. (modify, origanize)
- 해시태그 & 룰 & 커버 이미지 는 다음 이슈에서 진행예정입니다!

[REFACT]: 챌린지 organizeMode 일부 적용 

---

Projects/Data/DTO/Challenge/ChallengeDetail/ChallengeDetailResponseDTO.swift
Projects/Data/DataMapper/ChallengeDataMapper.swift
Projects/Domain/Entity/ChallengeDetail.swift
Projects/Presentation/Challenge/Implementations/Member/ChallengeCoordinator.swift
Projects/Presentation/Challenge/Implementations/Member/ChallengeViewController.swift
Projects/Presentation/Challenge/Implementations/Member/ChallengeViewModel.swift

[FEAT]: 챌린지 수정하기 기능 추가

---

Projects/Presentation/Challenge/Implementations/ChallengeOrganize/ChallengePreview/ChallengePreviewViewController.swift
Projects/Presentation/Challenge/Implementations/Member/ChallengeContainer.swift
Projects/Presentation/Challenge/Implementations/Member/ChallengeCoordinator.swift
Projects/Presentation/Challenge/Implementations/Member/ChallengeViewModel.swift
Projects/Presentation/Challenge/Implementations/Modify/ChallengeModifyContainer.swift
Projects/Presentation/Challenge/Implementations/Modify/ChallengeModifyCoordinator.swift
Projects/Presentation/Challenge/Implementations/Modify/ChallengeModifyViewController.swift
Projects/Presentation/Challenge/Implementations/Modify/ChallengeModifyViewModel.swift
Projects/Presentation/Challenge/Implementations/PresentationModel/ChallengeModifyPresentaionModel.swift
Projects/Presentation/Challenge/Implementations/PresentationModel/ChallengePreviewPresentationModel.swift

- #271 
챌린지 수정하기 화면 구현
화면이동 동작연결
챌린지 수정하기 화면에서 탭 제스처 연결
수정하기 화면 진입시 필요한데이터 파라미터로 전달
PresentationModel 분리

[FEAT]: 수정하기 UI 및 데이터 전달 & 화면이동 로직 구현

---

Projects/Presentation/MyPage/Implementations/FeedsByDate/FeedsByDateContainer.swift
Projects/Presentation/MyPage/Implementations/FeedsByDate/FeedsByDateCoordinator.swift
Projects/Presentation/MyPage/Implementations/FeedsByDate/FeedsByDateViewController.swift
Projects/Presentation/MyPage/Implementations/FeedsByDate/FeedsByDateViewModel.swift
Projects/Presentation/MyPage/Implementations/MyPageContainer.swift
Projects/Presentation/MyPage/Implementations/MyPageCoordinator.swift
Projects/Presentation/MyPage/Implementations/MyPageViewController.swift
Projects/Presentation/MyPage/Implementations/MyPageViewModel.swift
Projects/Presentation/MyPage/Implementations/PresentationModel/FeedsByDatePresentationModel.swift
Projects/Presentation/MyPage/Implementations/Views/FeedsByDate/FeedsByDateCell.swift
Projects/Presentation/MyPage/Implementations/Views/FeedsByDate/FeedsByDateImageView.swift
Projects/Presentation/MyPage/Implementations/Views/FeedsByDate/FeedsByDateTitleView.swift

[FEAT]: 마이 페이지 날짜별 피드 조회 UI 구현

---

Projects/Presentation/Challenge/Implementations/Member/Feed/FeedComment/FeedCommentViewController.swift

- #306 
피드 이미지 뷰 콘텐츠 모드 변경 (scale Aspect Fit - > scale Aspect Fill

[REFACT]: 이미지뷰 contentMode 수정

---

Projects/Presentation/Challenge/Implementations/ChallengeOrganize/ChallengePreview/ChallengePreviewViewController.swift
Projects/Presentation/Challenge/Implementations/Member/Feed/FeedComment/FeedCommentViewController.swift
Projects/Presentation/Challenge/Implementations/Member/Feed/FeedComment/Views/FeedCommentTopView.swift
Projects/Presentation/Challenge/Implementations/Modify/ChallengeModifyViewController.swift
Projects/Presentation/LogIn/Implementations/SignUp/EnterId/EnterIdViewController.swift
Projects/Presentation/LogIn/Implementations/SignUp/EnterPassword/EnterPasswordViewController.swift

- #308 
1. 챌린지 미리보기 토스트뷰 UI 수정 (팁추가)
2. 피드 신고하기 버튼 추가 및 신고기능 추가
3. 피드 탭 진입 시 게시물 모달 반복 노출 이슈
4. (ID & 비밀번호 찾기) 텍스트 필드 상태 변경 필요 (이미 수정 완료 되어있었음.)
5. (회원가입) 텍스트 필드 길이 - 좌우 마진 맞춰서 수정 필요

[REFACT]: QA수정사항 반영

---

Projects/Presentation/MyPage/Implementations/Views/FeedHistory/FeedHistoryCell.swift

- #312 
챌린지 인증내역 챌린지 이름 안나오는문제 - UI constraints 수정 (height 23)

[BUG]: 챌린지 타이틀 잘림 현상 수정

---

.gitignore
Projects/Core/Extensions/String+Extension.swift
Projects/Presentation/Challenge/Implementations/Member/Feed/Views/FeedCell.swift
Projects/Presentation/Challenge/Implementations/Member/Views/ChallengeTitleView.swift
Projects/Presentation/Home/Implementations/ChallengeHome/Views/HomeBottomView/HomeMyChallengeCell.swift
Projects/Presentation/Home/Implementations/ChallengeHome/Views/ProofChallegneCell/ChallengeImageView.swift
Projects/Presentation/LogIn/Implementations/SignUp/EnterEmail/VerifyEmail/VerifyEmailViewController.swift
Projects/Presentation/LogIn/Implementations/SignUp/EnterId/EnterIdViewController.swift

- #315 
- 아이디 검증 규칙 변경
- 이미지 contentMode 변경
- 회원가입 인증번호 안내문구 추가

[REFACT & FEAT] QA수정 3차

---

Projects/Data/DTO/LogIn/LogInRequestDTO.swift
Projects/Data/DTO/SignUp/Register/RegisterRequestDTO.swift
Projects/Data/DTO/SignUp/RequestVerficationCode/RequestVerificationCodeReqeustDTO.swift
Projects/Data/DTO/SignUp/VerifyCode/VerifyCodeRequestDTO.swift

- #320 
PROD모드일때, 빌드 안되는 버그 해결했습니다.

[BUG]: PROD일때, 빌드 안되는 버그 해결

---

Projects/Presentation/LogIn/Implementations/ResetPassword/TempPassword/TempPasswordViewController.swift
Projects/Presentation/LogIn/Implementations/SignUp/EnterEmail/VerifyEmail/VerifyEmailViewController.swift

[FEAT]: 비밀번호 변경 안내문구 추가

---

Projects/App/Info.plist

- #332 
카메라 접근 권환 및 사진첩 접근 권환 문구 수정

[REFACT]: 카메라 및 사진 접근 권환 문구 수정

---

Projects/App/Info.plist
Projects/App/Resources/Images/Images.xcassets/Contents.json
Projects/App/Sources/AppContainer.swift
Projects/App/Sources/AppLifeCycle/AppDelegate.swift
Projects/App/Sources/Splash/SplashViewController.swift
Projects/App/Sources/Splash/SplashViewModel.swift
Projects/Data/DTO/App/AppVersionRequestDTO.swift
Projects/Data/DTO/App/AppVersionResponseDTO.swift
Projects/Data/Repository/Implementations/AppRepositoryImpl/AppAPI.swift
Projects/Data/Repository/Implementations/AppRepositoryImpl/AppRepositoryImpl.swift
Projects/DesignSystem/Sources/Popup/Alert/AlertViewController.swift
Projects/DesignSystem/Sources/Popup/Alert/UIViewController+Alert.swift
Projects/Domain/Repository/Interfaces/AppRepository.swift
Projects/Domain/UseCase/Implementations/AppUseCaseImpl.swift
Projects/Domain/UseCase/Interfaces/AppUseCase.swift

- #347
https://github.com/user-attachments/assets/2f53ab6e-dbaa-49fe-bda8-381dfac48872

[FEAT]: 커스텀 Splash 화면 구현 및 앱 버전 확인 기능 구현
